### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Dan-chachan** [wustho/epy#1]
I'm on Linux. When I try to install with pip3, it throws a syntax error:

`
      File "/tmp/pip-req-build-xh4bvalo/epy.py", line 1113
        PROGRESSTR = f"{int(PROGRESS*100)}%"
`

Full error:
`    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-xh4bvalo/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-xh4bvalo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-xh4bvalo/pip-egg-info
         cwd: /tmp/pip-req-build-xh4bvalo/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-xh4bvalo/setup.py", line 3, in <module>
        from epy import __version__, __author__, __url__, __license__
      File "/tmp/pip-req-build-xh4bvalo/epy.py", line 1113
        PROGRESSTR = f"{int(PROGRESS*100)}%"
                                           ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by Dan-chachan** [comment]
So I edited the line to not use f-string, and the same error popped up except on a different line (1207), so f-string seems to be the problem

**Comment by wustho** [comment]
Whoa sorry. I deliberately ignored f string error warning in my editor since it still runs well in my laptop... I all fixed this. Thanks for debugging

**Comment by wustho** [comment]
https://github.com/wustho/epy/commit/2dd2bf341f18998165f67c12edd22ce94dae5ac5

Just learned that f-string is only supported for python v6 and above...

**Comment by Dan-chachan** [comment]
Haha, okay. Thanks for taking care of this, keep up the good work!
