### ISSUE TITLE
Request: Windows binary release

### ISSUE THREAD

**Issue by gd4c** [wustho/epy#14]
Is there any chance for a Windows binary? That would be great!

Thanks a lot

**Comment by wustho** [comment]
Sorry currently not using windows. But I see if I have a chance.

**Comment by gd4c** [comment]
That would be great!

**Comment by tionis** [comment]
With `python setup.py bdist --plat-name windows` you should be able to build a windows binary.  
I tried to put this into a github action but was stopped by some very weird errors on my end.

**Comment by wustho** [comment]
Should be automatically generated with GH Actions for now: https://github.com/wustho/epy/blob/master/.github/workflows/release-win.yml

eg. https://github.com/wustho/epy/releases/tag/v2022.4.18
