### ISSUE TITLE
Where is stored the bookmark file?

### ISSUE THREAD

**Issue by NicolasFlandrois** [wustho/epy#17]
Hi,

I am looking into the possibility to read books cross devices, and therefore the possibility to export/import bookmarks from a device to another (without transferring the entire book every time).

I can see through your code that you store the bookmark with the function `savestate()`. That same function creates `json.dump()` in a file.

My question then, where is that file stored?

Note: I installed your CLI app through pypi.org/`pip install`, and use it entirely in CLI. In my search through my device file system, `epy` is compiled. I don't see any json file around.

So I guess my questions are as follow:
- In Dev mode, where is the Json File stored?
- In compiled mode, where is the bookmark/json file stored? Or is it accessible?
- Is it in the pipelines to create some kind of "export my bookmarks" command? (If not, no worries, I'll find a way around)

Beside that query, I congratulate for a job well done!

**Comment by wustho** [comment]
Hey there, that's good idea, especially if it is possible to sync to cloud...

As for state file...
You can check by adding `-v` as an arg, eg. `epy -v`.
It will print version and absolute (path) locations of config file & state file being loaded.

It should be one of these:

- ~/.config/epy/state.json
- ~/.epy/state.json
- [Windows] %USERPROFILE%\epy\state.json

**Comment by NicolasFlandrois** [comment]
Super cool ! Thx!

FYI, initially, I thought to use the power of a git server. Syncking around all devices would be "easier".
But Yeah! cloud sync, on any platform could totally work!
