### ISSUE TITLE
Hourglass instead of opening epub

### ISSUE THREAD

**Issue by fabricalado** [wustho/epy#20]
I had epy installed previously and didn't have this problem, but since I powerwashed my Chromebook and re-installed epy, all I get when trying to open epubs is this:

![image](https://user-images.githubusercontent.com/20409882/108449038-a8fe8980-7217-11eb-88ab-d3b94dc1ecdb.png)

and then, when I crash the program with ctrl+c, I get this error message:
![image](https://user-images.githubusercontent.com/20409882/108449130-cf242980-7217-11eb-8bb6-648a1b18c85f.png)
so, apparently my error is this:
Keyerror: 'there is no item named 'OEBPS/../titlepage.xhtml' in the archive'

Any ideas?

P.S.: Thanks and congrats on the program! It's literally a sight for my sore eyes.

**Comment by wustho** [comment]
Hey there, is it happening only for one particular epub or others as well?

**Comment by fabricalado** [comment]
wow, that was quick!

I just checked and it seems to have happened only with this particular epub. Guess I'll try to re-download it and see if that fixes it.
The other message I got on a different epub was this: 
ERROR: Badly-structured ebook.
'Epub' object has no attribute 'toc'

My version is v2021.2.3

**Comment by wustho** [comment]
Ah, yes, indeed some epub isn't really compiled as it should be, best solution is to redownload same book with other sources...

As for: ERROR: Badly-structured ebook.
'Epub' object has no attribute 'toc'. I already have some ideas to fix it, just haven't had the time to implement it... Maybe will be in next commit...

**Comment by fabricalado** [comment]
My bad, it didn't occur to me to try with another epub before posting here.

Anyway, I'm glad it's solved, and thanks for all the effort you're putting into this!

**Comment by wustho** [comment]
https://github.com/wustho/epy/commit/6d89f3b440e46fd016ffb1973ce702d9a006b632
