### ISSUE TITLE
a way to disable mouse click to turn page? [Feature Request/ is it already possible]

### ISSUE THREAD

**Issue by autoteelar** [wustho/epy#25]
i usually click my windows to change them on my i3 instead of using keybinds, but clicking to turn page isnt the best ideal for me because i end up accidentially changing the page all the time, when i almost always use arrow keys to change page anyways, i got to thinking may be this would be a good feature to have

**Comment by wustho** [comment]
Ah, noted... Thanks for feedback, never thought of that...

**Comment by wustho** [comment]
Hey there, I just realized this is so simple. Just fixed this issue: https://github.com/wustho/epy/commit/b43ef4c87f654c8d3fed6d949be4ea784006145f

You might want to upgrade epy...

**Comment by autoteelar** [comment]
sure thing ^^ I'm a lil late but ill update now :D
