### ISSUE TITLE
Copying text

### ISSUE THREAD

**Issue by jghauser** [wustho/epy#26]
Thanks for the great piece of software!

Is it possible to copy text? I can do that in epr, but it seems like in epy, I can only use the mouse for navigation. I prefer epy's features, but copying text is quite important for me.

**Comment by wustho** [comment]
Hey there, thanks... I think I can make an options to disable mouse support like someone suggested in https://github.com/wustho/epy/issues/25

Will do it right away but unfortunately not this week...

**Comment by jghauser** [comment]
Thanks, looking forward to this! Happy to wait until you have the time to implement it :)

**Comment by wustho** [comment]
Hey there, I just realized this is so simple. Just fixed this issue: https://github.com/wustho/epy/commit/b43ef4c87f654c8d3fed6d949be4ea784006145f

You might want to upgrade epy...

**Comment by jghauser** [comment]
Just tested, it works! Thanks for getting this moving so quickly!
