### ISSUE TITLE
Add command line option to send keys to epy on startup

### ISSUE THREAD

**Issue by reportaman** [wustho/epy#31]
Just like in vim, it would be nice to be able to send keys to epy on startup. An option like ``>>epy --keys "<Tab>gg"`` would open epy with contents page open, and cursor on the first contents line item.

If thats difficult, please add a command line option to specify start screen, ``>>epy -s contents`` would start epy and launch contents page (as if ``<Tab>`` was entered).

**Comment by wustho** [comment]
Hmm, this might be good for code editor, but I don't think this is necessary for ebook reader. Beside, so much ebook files do not conform to the structure standard, some even don't have any toc navigation points.
