### ISSUE TITLE
is there a way to change the editor that is used when pressing e?

### ISSUE THREAD

**Issue by autoteelar** [wustho/epy#37]
it uses nano for me by default, which is a good editor but i usually prefer using mousepad, is there a way to change it?

**Comment by wustho** [comment]
That's weird. I don't think epy will open any editor in any way.

**Comment by autoteelar** [comment]
wait it doesnt for me either, why'd i even make this post then? @.@ maybe i was using some other program, oops 😝

**Comment by autoteelar** [comment]
ooh i remember, i was using lyrics-in-terminal, :D

**Comment by mcepl** [comment]
I guess this should be closed then.

**Comment by wustho** [comment]
@mcepl yes, sorry, I kept some issues open because of there is better documentation in issues than readme...
