### ISSUE TITLE
TTS doesn't work with other languages than en_US

### ISSUE THREAD

**Issue by mcepl** [wustho/epy#42]
And frankly, Harry Potter fanfiction should be read in `en_GB` ;).

Also, would it be possible to switch to [mimic](https://mimic.mycroft.ai/). It is free (contrary to svox, which cannot go into most Linux distributions) and it has stdin-to-speech function, so no need to fiddle with temporary files. Difference in the pronunciation is minimal.

**Comment by wustho** [comment]
Thanks! Also thanks to mimic suggestion, will look into that...
