### ISSUE TITLE
crash in the wrapper function

### ISSUE THREAD

**Issue by mcepl** [wustho/epy#48]
```
fanfiction@stitny$ epy elsewhere_at_hogwarts/Thursdays.epub
Traceback (most recent call last):
  File "/home/matej/.local/bin/epy", line 33, in <module>
    sys.exit(load_entry_point('epy-reader', 'console_scripts', 'epy')())
  File "/home/matej/archiv/knihovna/repos/tmp/epy/epy.py", line 3469, in main
    curses.wrapper(preread, filepath)
  File "/usr/lib64/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/matej/archiv/knihovna/repos/tmp/epy/epy.py", line 3326, in preread
    reading_state = reader.read(reading_state)
  File "/home/matej/archiv/knihovna/repos/tmp/epy/epy.py", line 2905, in read
    rettock, fllwd, _ = self.toc(toc_entries, ntoc)
  File "/home/matej/archiv/knihovna/repos/tmp/epy/epy.py", line 1740, in wrapper
    strs = "  " + i.replace("\n", " ")
AttributeError: 'NoneType' object has no attribute 'replace'
fanfiction@stitny$
```

**Comment by wustho** [comment]
Hey there, thanks for detailed traceback. If you don't mind, can I know where I can download that epub?

Seems like anomaly from the epub structure. I think the fix should be simple. But I also think it's better for the fix to be specific to how fundamental the anomaly is ...

**Comment by mcepl** [comment]
> Hey there, thanks for detailed traceback. If you don't mind, can I know where I can download that epub?

https://mcepl.fedorapeople.org/tmp/Thursdays.epub

I am not sure, where I’ve got this … ah, I see https://hayseed42.wordpress.com/2014/06/27/getting-the-hang-of-thursdays-0122/ … that could be some pretty bad conversion via pandoc or something of that kind. So, yes, `epy` shouldn't crash on any EPub, but don't sweat over this too much.

**Comment by wustho** [comment]
@mcepl Hey there, just fixed it with this: https://github.com/wustho/epy/commit/282270a51d9d52689f6362f17b760d6cb1d3dac6
Thanks for traceback...

**Comment by mcepl** [comment]
Thank you, I will test. It seems to work so far.

**Comment by mcepl** [comment]
Hmm, it somehow went away.
