### ISSUE TITLE
Empty search string causes AssertionError

### ISSUE THREAD

**Issue by dreamlayers** [wustho/epy#73]
I start reading an epub book, then hit the `/` key to start a search, and press enter without entering a search string. This is the result (with epy path removed to simplify it):
```
Traceback (most recent call last):
  File "epy.py", line 3976, in <module>
    main()
  File "epy.py", line 3966, in main
    filepath = curses.wrapper(preread, filepath)
  File "/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "epy.py", line 3865, in preread
    reading_state_or_ebook = reader.read(reading_state)
  File "epy.py", line 3483, in read
    ret_object = self.searching(
  File "epy.py", line 2719, in searching
    assert isinstance(candidate_text, NoUpdate) or isinstance(candidate_text, Key)
AssertionError
```
This is in Ubuntu 22.10 with Python 3.10.7. Both cloning from here and installing via pip gives the same result. I think the proper thing to do would be to assume the user doesn't want to perform a search and get rid of the search prompt. I do see that this can be accomplished by pressing escape.

**Comment by 3N4N** [comment]
This patch should fix it:

```
diff --git a/epy.py b/epy.py
index b9b1c1e400d5..edb6f711bbce 100755
--- a/epy.py
+++ b/epy.py
@@ -2723,6 +2723,8 @@ class Reader:
             # if isinstance(candidate_text, str) and candidate_text != "":
             if isinstance(candidate_text, str) and candidate_text:
                 self.search_data = SearchData(value=candidate_text)
+            elif candidate_text == "":
+                return candidate_text
             else:
                 assert isinstance(candidate_text, NoUpdate) or isinstance(candidate_text, Key)
                 return candidate_text
```

You can apply it thusly:
- Copy the diff above to clipboard
- Run `patch -p1`
- Paste the content of the clipboard into the terminal (probably with Ctrl-Shift-V)
- Exit (Ctrl-D in Linux or Ctrl-Z+Enter in Windows)

@wustho does this seem alright?  You can patch it into master, then.

**Comment by wustho** [comment]
Hey guys, fixed with: https://github.com/wustho/epy/commit/fed6dc9e14566408bf527ea123092ce5511e05e9
Thanks!

**Comment by dreamlayers** [comment]
Yes, this fixes the issue. Thank you!
