### ISSUE TITLE
How to go through search matches?

### ISSUE THREAD

**Issue by DUOLabs333** [wustho/epy#79]
I can press '/' and search for a word, it's not clear how to go to next/previous matches.

**Comment by wustho** [comment]
Hey there, can you try "n" for next occurence, and "N" for previous?

**Comment by DUOLabs333** [comment]
It works (I seem to have thought it was Ctrl+n, not Shift+n --- is there a way to configure this)!

**Comment by mcepl** [comment]
vi-like movement is copy from `less(1)`, I guess, which is what epy resembles a lot.
