### ISSUE TITLE
[Asking] How to hide underline

### ISSUE THREAD

**Issue by haunt98** [wustho/epy#82]
When I use epy I see underline

<img width="841" alt="image" src="https://user-images.githubusercontent.com/5424272/215344246-f60e835c-a9c8-4c26-8b67-e8bb9390582a.png">

How do I disable them?

**Comment by wustho** [comment]
That's weird. Does that happen for that specific ebook or other ebooks as well?

**Comment by haunt98** [comment]
I have 3 epub, they all have that underline.

Maybe because I use kitty terminal ?

**Comment by haunt98** [comment]
Looks like my theme is messed up. Thanks @wustho
