### ISSUE TITLE
AUR epy-git: pkgver() error

### ISSUE THREAD

**Issue by xiota** [wustho/epy#89]
Noticed you are the maintainer of `epy-git` on AUR.  It is failing to build.
```
==> Starting pkgver()...
==> ERROR: pkgver is not allowed to contain colons, forward slashes, hyphens or whitespace.
==> ERROR: pkgver() generated an invalid version: grep: epy.py: No such file or directory
.r286.c7a87f3
```

Fix is pretty simple.
```
pkgver() {
  cd "$_name"
  printf "%s.r%s.%s" \
    "$(grep -RF --include=*.py '__version__ = ' | awk -F\" '{print $2}')" \
    "$(git rev-list --count HEAD)" \
    "$(git rev-parse --short HEAD)"
}
```

Also, here is a [PKGBUILD](https://github.com/wustho/epy/files/11170581/PKGBUILD.txt) for your other ereader, [baca](https://github.com/wustho/baca), in case you want to create and maintain it.

If you add me as comaintainer for `epy-git` and `baca-ereader-git` (after you create it; there is an entirely different program called `baca-cli`), I can help keep them up to date.  (Or I can create it and add you as comaintainer, if that's easier for you.)

**Comment by wustho** [comment]
Yess, that would be much appreciated! I think it's better for you to create new. I no longer use Arch, so I cannot interact with AUR and no need for you to add me as comaintainer... Thanks man, let me know if there's anything I can do...

**Comment by xiota** [comment]
It is here: [baca-ereader-git](https://aur.archlinux.org/packages/baca-ereader-git)

About the `epy-git` pkgver() another option is to drop the initial version string entirely:
```
  printf "r%s.%s" \
    "$(git rev-list --count HEAD)" \
    "$(git rev-parse --short HEAD)"
```

It's less prone to breaking.

**Comment by xiota** [comment]
I'll do my best to keep the `baca-ereader-git` package functional.

**Comment by xiota** [comment]
> I no longer use Arch, so I cannot interact with AUR

To clarify, you're unable to fix the pkgver error yourself and also unable to log onto the `epy-git` AUR page to add me as comaintainer so I can fix it?  If so, would you mind if I send a request to orphan the package so I can adopt and update it?

**Comment by wustho** [comment]
Not at all, in fact, thanks for that!

**Comment by Antiz96** [comment]
@wustho Are you able to log in to the [AUR web interface](https://aur.archlinux.org/) to disown the package so xiota can take over the maintenance?

@xiota  While waiting for wustho to disown the package or for the orphan request to get through (we have to wait 14 days before being able to accept it), I made you a co-maintainer for the `epy-git` package so you can push changes right away ;)

**Comment by wustho** [comment]
Wow you guys made me feel high spirited about this app, might refactor this later so it's easier for other devs to contribute. Will try to do it @Antiz96 I think I still have the credentials.

**Comment by wustho** [comment]
@Antiz96 just did!

**Comment by Antiz96** [comment]
> @Antiz96 just did! Thanks guys!

Cool, thanks a lot!

@xiota, you're now the maintainer of the `epy-git` AUR package ;)
I'm closing your orphan request.

**Comment by xiota** [comment]
Thanks for the great programs.  I just updated the AUR package, and will do my best to keep it up to date.
